theme: jekyll-theme-minimal
title: [I'm Ma Xinran]
description: [Welcome to XLearning Lab!]
logo: ./portrait.png
url: https://allenHearst.github.io/maxinran.github.io
email: xinranma.gm@gmail.com
RSS: false
github_username: allenHearst

timezone: China/Beijing

markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]
