theme: jekyll-theme-minimal
title: I'm Ma Xinran.
description: Sichuan University, China
logo: ./portrait.png
url: https://allenHearst.github.io/
email: xinranma.gm@gmail.com
RSS: false
github_username: allenHearst

timezone: Asia/Shanghai


